#!/bin/bash
# Create an account on RTE API website (https://data.rte-france.com/)
# Register to the Ecowatt API (https://data.rte-france.com/catalog/-/api/consumption/Ecowatt/v4.0) and click on "Abonnez-vous à l'API" 
# Create a new application
# Copy the base64 encoded id and secret
# API quota restriction: 
# The quota value is one call every 15 minutes

ECOFILE="/tmp/ecowatt.json"
RTE_AUTH="<your base64 keys>" # sbase64 auth token;
TOKEN=$(curl -sXPOST https://digital.iservices.rte-france.com/token/oauth/ -H "Authorization: Basic ${RTE_AUTH}" | jq -r  '.["access_token"]')
`curl -sH'Authorization: Bearer '$TOKEN https://digital.iservices.rte-france.com/open_api/ecowatt/v4/signals --output $ECOFILE`
DVALUE=`jq '.[][].dvalue' $ECOFILE |uniq`
if [[ $DVALUE == "1" ]]; then
    echo "Consommation - OK"
    exit 0
elif [[ $DVALUE =~ .*"2".* ]]; then
        for day in {0..3}
        do 
            for timerange in `jq -r ".[][$day].values[] |select(.hvalue == 2) |.pas" $ECOFILE`
            do
                date=`jq -r ".[][$day].jour" $ECOFILE`
                echo "RTE Warning - $date - between $timerange:00 and $timerange:59"
            done 
        done        
    exit 1
elif [[ $DVALUE =~ .*"3".* ]]; then
        for day in {0..3}
        do 
            for timerange in `jq -r ".[][$day].values[] |select(.hvalue == 3) |.pas" $ECOFILE`
            do
                date=`jq -r ".[][$day].jour" $ECOFILE`
                echo "RTE Critical - $date - between $timerange:00 and $timerange:59"
            done 
        done        
    exit 2
else
    echo "Consommation - UNKNOWN"
    exit 3
fi

# Output 
# RTE Critical - 2022-09-29T00:00:00+02:00 - between 6:00 and 6:59
# RTE Critical - 2022-10-01T00:00:00+02:00 - between 10:00 and 10:59
# RTE Warning - 2022-09-29T00:00:00+02:00 - between 8:00 and 8:59
